import flagsJson from "../../public/flags/flags.json";

const FLAGS: Record<string, string> = flagsJson;

// ISO 3166-1 alpha-2 → name as keyed in flags.json
const ISO_TO_NAME: Record<string, string> = {
  AR: "Argentina",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BH: "Bahrain",
  BD: "Bangladesh",
  BY: "Belarus",
  BE: "Belgium",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BR: "Brazil",
  BG: "Bulgaria",
  KH: "Cambodia",
  CA: "Canada",
  CL: "Chile",
  CN: "China",
  CO: "Colombia",
  CI: "Cote D'Ivoire",
  CU: "Cuba",
  CZ: "Czech Republic",
  CS: "Czechoslovakia",
  DK: "Denmark",
  DD: "East Germany",
  EG: "Egypt",
  EE: "Estonia",
  FI: "Finland",
  FR: "France",
  GE: "Georgia",
  DE: "Germany",
  GR: "Greece",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  XK: "Kosovo",
  LV: "Latvia",
  LB: "Lebanon",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MK: "Macedonia",
  MY: "Malaysia",
  ML: "Mali",
  MT: "Malta",
  MX: "Mexico",
  MN: "Mongolia",
  MA: "Morocco",
  NL: "Netherlands",
  NZ: "New Zealand",
  NG: "Nigeria",
  KP: "North Korea",
  GB: "United Kingdom",
  NO: "Norway",
  PK: "Pakistan",
  PS: "Palestinian Territory",
  PE: "Peru",
  PH: "Philippines",
  PL: "Poland",
  PT: "Portugal",
  RO: "Romania",
  RU: "Russia",
  WS: "Samoa",
  RS: "Serbia",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  ZA: "South Africa",
  KR: "South Korea",
  SU: "Soviet Union",
  ES: "Spain",
  SZ: "Swaziland",
  SE: "Sweden",
  CH: "Switzerland",
  TW: "Taiwan",
  TH: "Thailand",
  TK: "Tokelau",
  TR: "Turkey",
  VI: "US Virgin Islands",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  US: "United States of America",
  UY: "Uruguay",
  VE: "Venezuela",
  VN: "Vietnam",
  YU: "Yugoslavia",
};

export function getFlagPath(countryCode: string): string | null {
  // Try direct lookup by name (in case origin_country stores full names)
  const directFile = FLAGS[countryCode];
  if (directFile) return `/flags/${directFile}`;

  // Try ISO 2-letter code lookup
  const name = ISO_TO_NAME[countryCode.toUpperCase()];
  if (!name) return null;
  const file = FLAGS[name];
  return file ? `/flags/${file}` : null;
}
